### ISSUE TITLE
With Mappable Pod 

### ISSUE THREAD

**Issue by SanjayRathor** [pisces/APNSUtil#6]
Hi,

can we use it without the Mappable pod also i will get the registration id

**Comment by pisces** [comment]
Hi.
You can use like that u want but i need some coding.
I will add code that as soon as i can.
Please wait some days.

Thanks your feedback.


2019년 1월 23일 (수) 오전 12:10, sohamshukla1982 <notifications@github.com>님이 작성:

**Comment by pisces** [comment]
1.2.0 released.
You can use APNSUtil without ObjectMapper.
